zipSelect :
	zip u25026560.zip BubbleTeaShop.cpp Menus.cpp getTeaName.png getTeaPrice.png processTeaOption.png processOrder.png main.cpp

compile :
	g++ -Werror -Wall -std=c++98 -g *.cpp -o main

reset :
	rm *.zip
	rm main
